/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.controller.admin;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.shiro.authz.annotation.Logical;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.ccloud.core.JBaseCRUDController;
import org.ccloud.core.interceptor.ActionCacheClearInterceptor;
import org.ccloud.interceptor.UCodeInterceptor;
import org.ccloud.route.RouterMapping;
import org.ccloud.route.RouterNotAllowConvert;
import org.ccloud.utils.StringUtils;
import org.ccloud.model.Brand;
import org.ccloud.model.Goods;
import org.ccloud.model.GoodsCategory;
import org.ccloud.model.Supplier;
import org.ccloud.model.query.BrandQuery;
import org.ccloud.model.query.GoodsCategoryQuery;
import org.ccloud.model.query.GoodsQuery;
import org.ccloud.model.query.SupplierQuery;

import com.alibaba.fastjson.JSON;
import com.google.common.collect.ImmutableMap;
import com.jfinal.aop.Before;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;
/**
 * Generated by 九毫米(http://9mm.tech).
 */
@RouterMapping(url = "/admin/category", viewPath = "/WEB-INF/admin/goods_category")
@Before(ActionCacheClearInterceptor.class)
@RouterNotAllowConvert
@RequiresPermissions(value={"/admin/category","/admin/all"},logical=Logical.OR)
public class _GoodsCategoryController extends JBaseCRUDController<GoodsCategory> {
	
	@Override
	public void index() {
		render("index.html");
	}	

	public void list() {
        String keyword = getPara("k");
        if (StrKit.notBlank(keyword)) {
            keyword = StringUtils.urlDecode(keyword);
            setAttr("k", keyword);
        }
        
        String parentId = getPara("parentId", "0");

        Page<GoodsCategory> page = GoodsCategoryQuery.me().
        		paginate(getPageNumber(), getPageSize(), parentId, keyword, "cc.order_list asc");
        Map<String, Object> map = ImmutableMap.of("total", page.getTotalRow(), "rows", page.getList());
        renderJson(map);		
		
	}
	
	@Override
	public void save() {
		
		final GoodsCategory category = getModel(GoodsCategory.class);
		if (StringUtils.isBlank(category.getId())) {
			category.setIsParent(0);
		}
		if (category.saveOrUpdate()) {
			GoodsCategoryQuery.me().updateParent(category);
			renderAjaxResultForSuccess("ok");
		} else {
			renderAjaxResultForError("false");
		}
	}
	
	@Override
	@RequiresPermissions(value={"/admin/category/edit","/admin/all"},logical=Logical.OR)
	public void edit() {
		String id = getPara("id");
		if (id != null) {
			GoodsCategory category = GoodsCategoryQuery.me().findById(id);
			setAttr("goodsCategory", category);
			
			List<Brand> list = BrandQuery.me().findBySupplierId(category.getSupplierId());
			setAttr("blist", list);
		}
		List<Supplier> list = SupplierQuery.me().findAll();
		setAttr("list", list);
	}
	
	@Before(UCodeInterceptor.class)
	@RequiresPermissions(value={"/admin/category/edit","/admin/all"},logical=Logical.OR)
	public void batchDelete() {
		String[] ids = getParaValues("dataItem");
		int count = GoodsCategoryQuery.me().batchDelete(ids);
		if (count > 0) {
			renderAjaxResultForSuccess("删除成功");
		} else {
			renderAjaxResultForError("删除失败!");
		}
		
	}
	
	@Override
	@RequiresPermissions(value={"/admin/category/edit","/admin/all"},logical=Logical.OR)
	@Before(Tx.class)
	public void delete() {
		String id = getPara("id");
		final GoodsCategory category = GoodsCategoryQuery.me().findById(id);
		if (category != null) {
            List<String> ids = new ArrayList<>();
            boolean status = this.deleteCheck(category, ids);
            if (!status) {
            	renderAjaxResultForError("分类下已有商品");
            	return;
            }
            int count = GoodsCategoryQuery.me().batchDelete(ids);
            if (count > 0) {
                renderAjaxResultForSuccess("删除成功");
            } else {
                renderAjaxResultForError("删除失败");
            }
		}
		GoodsCategoryQuery.me().updateParent(category);
	}
	
	//递归获取所有子节点ID并判断分类下是否含有商品
	private boolean deleteCheck(GoodsCategory categoryInfo, List<String> ids) {
		List<Goods> list = GoodsQuery.me().findByCategory(categoryInfo.getId());
		if (list.size() > 0) {
			return false;
		}
		ids.add(categoryInfo.getId());
		if (categoryInfo.getIsParent() > 0) {
			List<GoodsCategory> categoryList = GoodsCategoryQuery.me().findByParentId(categoryInfo.getId());
			for (GoodsCategory goodsCategory : categoryList) {
				boolean status = this.deleteCheck(goodsCategory, ids);
				if (!status) {
					return false;
				}
			}
		}
		return true;
	}
	
	public void category_tree() {
		List<Map<String, Object>> list = GoodsCategoryQuery.me().findCategoryListAsTree(1);
		setAttr("treeData", JSON.toJSON(list));
	}
	
	public void getBrand() {
        String id = getPara("supplierid");
        List<Brand> brands = BrandQuery.me().findBySupplierId(id);
        List<Map<String, Object>> list = new ArrayList<>();

        for (Brand brand : brands) {
            Map<String, Object> map = new HashMap<>();

            map.put("id", brand.getId());
            map.put("name", brand.getName());

            list.add(map);
        }

        renderJson(list);
	}
	
	@RequiresPermissions(value={"/admin/category/edit","/admin/all"},logical=Logical.OR)
	public void enable() {
		String id = getPara("id");
		int state = getParaToInt("state");
		GoodsCategory goodsCategory = GoodsCategoryQuery.me().findById(id);
		goodsCategory.setState(state);
		goodsCategory.update();
		renderAjaxResultForSuccess("更新成功");
	}	
	
}
