/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.controller.admin;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.lang.time.DateFormatUtils;
import org.ccloud.Consts;
import org.ccloud.core.JBaseCRUDController;
import org.ccloud.core.interceptor.ActionCacheClearInterceptor;
import org.ccloud.route.RouterMapping;
import org.ccloud.route.RouterNotAllowConvert;
import org.ccloud.utils.StringUtils;
import org.ccloud.model.Product;
import org.ccloud.model.PurchaseOrder;
import org.ccloud.model.PurchaseOrderDetail;
import org.ccloud.model.Seller;
import org.ccloud.model.Supplier;
import org.ccloud.model.User;
import org.ccloud.model.query.ProductQuery;
import org.ccloud.model.query.PurchaseOrderQuery;
import org.ccloud.model.query.SellerQuery;
import org.ccloud.model.query.SupplierQuery;

import com.alibaba.fastjson.JSON;
import com.jfinal.aop.Before;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.tx.Tx;
/**
 * Generated by 九毫米(http://9mm.tech).
 */
@RouterMapping(url = "/admin/purchaseOrderDetail", viewPath = "/WEB-INF/admin/purchase_order_detail")
@Before(ActionCacheClearInterceptor.class)
@RouterNotAllowConvert
public class _PurchaseOrderDetailController extends JBaseCRUDController<PurchaseOrderDetail> { 
	
	@Override
	public void index() {
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		String supplierId = getPara("supplierId");
		List<Product> productlist = ProductQuery.me().findAllByUser(user.getId(),user.getDataArea(),supplierId);
		
		Map<String, Object> productInfoMap = new HashMap<String, Object>();
		List<Map<String, String>> productOptionList = new ArrayList<Map<String, String>>();
		
		for (Product record : productlist) {
			Map<String, String> productOptionMap = new HashMap<String, String>();
			
			String productId = record.getStr("id");
			String customName = record.getStr("name");
			String productNamePig = record.getStr("cps_name");
			
			productInfoMap.put(productId, record);
			
			productOptionMap.put("id", productId);
			productOptionMap.put("text", customName+"/"+productNamePig);
			
			productOptionList.add(productOptionMap);
		}
		
		Supplier supplier = SupplierQuery.me().findById(supplierId);
		
		
		setAttr("productInfoMap", JSON.toJSON(productInfoMap));
		setAttr("productOptionList", JSON.toJSON(productOptionList));
		
		setAttr("supplierInfoMap", JSON.toJSON(supplier));
		
		setAttr("deliveryDate", DateFormatUtils.format(new Date(), "yyyy-MM-dd"));
		
		render("index.html");
	}
		
	public void list(){
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		List<Product> list = ProductQuery.me().findAllByUserId(user.getId(),user.getDataArea());
		renderJson(list);
	}
	
	public void showTr(){
		String id = getPara("id");
		Product product = ProductQuery.me().findByPId(id);
		renderJson(product);
	}
	
	//采购订单生成
	@Override
	@Before(Tx.class)
	public void save() {
		final PurchaseOrder purchaseOrder =getModel(PurchaseOrder.class);
		final PurchaseOrderDetail purchaseOrderDetail = getModel(PurchaseOrderDetail.class);
		Map<String, String[]> paraMap = getParaMap();
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		Seller seller = SellerQuery.me().findByUserId(user.getId());
		int i = PurchaseOrderQuery.me().findByUserId(user.getId(),user.getDataArea());
		/*采购订单：PO + 100000(机构编号或企业编号6位,这里取销售商编码) + 20171108(时间) + 000001(流水号)*/
		i++;
		String j=Integer.toString(i);
		int countt =j.length();
		for(int m=0;m<(6-countt);m++){
			j= "0"+j;
		}
		Date date = new Date();
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMddHHmmss");
		String str = sdf.format(date);
		String porderSn = "PO"+seller.getSellerCode().substring(0, 6)+str.substring(0,8)+j;
		Date date1 = new Date();
		String Id = StrKit.getRandomUUID();
		purchaseOrder.set("id", Id);
		purchaseOrder.set("porder_sn", porderSn);
		purchaseOrder.set("supplier_id", StringUtils.getArrayFirst(paraMap.get("supplierId")));
		purchaseOrder.set("contact", StringUtils.getArrayFirst(paraMap.get("contact")));
		purchaseOrder.set("mobile", StringUtils.getArrayFirst(paraMap.get("mobile")));
		purchaseOrder.set("biz_user_id", user.getId());
		purchaseOrder.set("biz_date", date1);
		purchaseOrder.set("status", 0);
		purchaseOrder.set("total_amount", StringUtils.getArrayFirst(paraMap.get("total")));
		purchaseOrder.set("payment_type", StringUtils.getArrayFirst(paraMap.get("paymentType")));
		purchaseOrder.set("remark", StringUtils.getArrayFirst(paraMap.get("remark")));
		purchaseOrder.set("dept_id", user.getDepartmentId());
		purchaseOrder.set("data_area", user.getDataArea());
		purchaseOrder.set("deal_date", StringUtils.getArrayFirst(paraMap.get("deliveryDate")));
		purchaseOrder.set("create_date", date1);
		purchaseOrder.save();
		
		String productNumStr = StringUtils.getArrayFirst(paraMap.get("productNum"));
		Integer productNum = Integer.valueOf(productNumStr);
		
		int a = 0;
		int b = 0;
		Set<String> set = new HashSet<String>();
		while (productNum > a) {
				b++;
				String productId = StringUtils.getArrayFirst(paraMap.get("productId" + b));
				set.add(productId);
				a++;
			}
		if(set.size()<productNum){
			renderAjaxResultForError("订单中有两件及以上相同的产品，请重新选择！");
			return;
		}
		
		Integer count = 0;
		Integer index = 0;
		
		while (productNum > count) {
			index++;
			String productId = StringUtils.getArrayFirst(paraMap.get("productId" + index));
			Product product = ProductQuery.me().findByUserId(user.getId(),productId);
			int big =product.getConvertRelate();
			if (StrKit.notBlank(productId)) {
				String Id2 = StrKit.getRandomUUID();
				String rowTotal=StringUtils.getArrayFirst(paraMap.get("inputRowTotal"+ index));
				purchaseOrderDetail.set("id", Id2);
				purchaseOrderDetail.set("purchase_order_id", Id);
				purchaseOrderDetail.set("product_id", productId);
				purchaseOrderDetail.set("product_count", (Integer.parseInt(StringUtils.getArrayFirst(paraMap.get("smallNum"+ index)))+Integer.parseInt(StringUtils.getArrayFirst(paraMap.get("bigNum"+ index)))*big));
				purchaseOrderDetail.set("product_amount", rowTotal);
				purchaseOrderDetail.set("product_price", StringUtils.getArrayFirst(paraMap.get("bigPrice"+ index)));
				purchaseOrderDetail.set("order_list",index);
				purchaseOrderDetail.set("create_date", date1);
				purchaseOrderDetail.set("dept_id", user.getDepartmentId());
				purchaseOrderDetail.set("data_area", user.getDataArea());
				purchaseOrderDetail.save();
				
				count++;
			}

		}
		renderAjaxResultForSuccess();

	}
	public void show_supplier(){
		List<Supplier> suppliers = SupplierQuery.me().findAll();
		renderJson(suppliers);
	}
}
