/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.controller.admin;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.poi.ss.usermodel.Workbook;
import org.apache.shiro.authz.annotation.Logical;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.ccloud.Consts;
import org.ccloud.core.JBaseCRUDController;
import org.ccloud.core.interceptor.ActionCacheClearInterceptor;
import org.ccloud.model.Customer;
import org.ccloud.model.CustomerJoinCustomerType;
import org.ccloud.model.CustomerType;
import org.ccloud.model.Department;
import org.ccloud.model.SellerCustomer;
import org.ccloud.model.User;
import org.ccloud.model.UserJoinCustomer;
import org.ccloud.model.query.CustomerJoinCustomerTypeQuery;
import org.ccloud.model.query.CustomerQuery;
import org.ccloud.model.query.CustomerTypeQuery;
import org.ccloud.model.query.DepartmentQuery;
import org.ccloud.model.query.SellerCustomerQuery;
import org.ccloud.model.query.UserJoinCustomerQuery;
import org.ccloud.model.query.UserQuery;
import org.ccloud.model.vo.CustomerExcel;
import org.ccloud.route.RouterMapping;
import org.ccloud.route.RouterNotAllowConvert;
import org.ccloud.utils.DataAreaUtil;
import org.ccloud.utils.StringUtils;

import com.alibaba.fastjson.JSON;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Lists;
import com.jfinal.aop.Before;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.tx.Tx;

import cn.afterturn.easypoi.excel.ExcelExportUtil;
import cn.afterturn.easypoi.excel.ExcelImportUtil;
import cn.afterturn.easypoi.excel.entity.ExportParams;
import cn.afterturn.easypoi.excel.entity.ImportParams;

/**
 * Generated by 九毫米(http://9mm.tech).
 */
@RouterMapping(url = "/admin/sellerCustomer", viewPath = "/WEB-INF/admin/seller_customer")
@Before(ActionCacheClearInterceptor.class)
@RouterNotAllowConvert
public class _SellerCustomerController extends JBaseCRUDController<SellerCustomer> {

	@RequiresPermissions(value = { "/admin/sellerCustomer", "/admin/dealer/all", "/admin/all" }, logical = Logical.OR)
	public void index() {
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer", "/admin/dealer/all", "/admin/all" }, logical = Logical.OR)
	public void list() {

		String selectDataArea = getSessionAttr(Consts.SESSION_SELECT_DATAAREA);

		Map<String, String[]> paraMap = getParaMap();
		String keyword = StringUtils.getArrayFirst(paraMap.get("k"));
		if (StrKit.notBlank(keyword)) {
			keyword = StringUtils.urlDecode(keyword);
		}

		Page<Record> page = SellerCustomerQuery.me().paginate(getPageNumber(), getPageSize(), keyword, selectDataArea);
		List<Record> customerList = page.getList();

		Map<String, Object> map = ImmutableMap.of("total", page.getTotalRow(), "rows", customerList);
		renderJson(map);
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/edit", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void edit() {
		String id = getPara("id");
		String selectDataArea = getSessionAttr(Consts.SESSION_SELECT_DATAAREA);

		if (StrKit.notBlank(id)) {
			Record sellerCustomer = SellerCustomerQuery.me().findMoreById(id);
			setAttr("sellerCustomer", sellerCustomer);

			List<Record> list = UserJoinCustomerQuery.me().findUserListBySellerCustomerId(id, selectDataArea);

			int length = list.size();
			String[] userIds = new String[length];
			String[] realnames = new String[length];

			for (int i = 0; i < length; i++) {
				userIds[i] = list.get(i).getStr("user_id");
				realnames[i] = list.get(i).getStr("realname");
			}

			setAttr("cUserIds", StrKit.join(userIds, ","));
			setAttr("cUserNames", StrKit.join(realnames, ","));

			setAttr("cTypeList", CustomerJoinCustomerTypeQuery.me().findCustomerTypeListBySellerCustomerId(id,
					DataAreaUtil.getUserDealerDataArea(selectDataArea)));
		}

		List<CustomerType> customerTypeList = CustomerTypeQuery.me()
				.findByDataArea(DataAreaUtil.getUserDealerDataArea(selectDataArea));
		setAttr("customerTypeList", customerTypeList);

	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/edit", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void enable() {

		String id = getPara("id");
		int isEnabled = getParaToInt("isEnabled");

		if (SellerCustomerQuery.me().enable(id, isEnabled)) {
			renderAjaxResultForSuccess();
		} else {
			renderAjaxResultForError();
		}

	}

	@Before(Tx.class)
	@RequiresPermissions(value = { "/admin/sellerCustomer/edit", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void save() {

		String sellerId = getSessionAttr("sellerId");

		SellerCustomer sellerCustomer = getModel(SellerCustomer.class);
		Customer customer = getModel(Customer.class);

		String customerId = "";
		String sellerCustomerId = "";
		// 检查客户是否存在
		Customer persiste = CustomerQuery.me().findByCustomerNameAndMobile(customer.getCustomerName(),
				customer.getMobile());

		if (persiste == null) {
			customerId = StrKit.getRandomUUID();
			customer.set("id", customerId);
			customer.set("create_date", new Date());
			customer.save();
		} else {
			customerId = persiste.getId();
			customer.set("id", customerId);
			customer.set("modify_date", new Date());
			customer.update();
		}

		sellerCustomer.set("seller_id", sellerId);
		sellerCustomer.set("customer_id", customerId);
		sellerCustomer.set("is_enabled", 1);
		sellerCustomer.set("is_archive", 1);
		User loginUser=getSessionAttr(Consts.SESSION_LOGINED_USER);
		String dept_dataArea = DataAreaUtil.getUserDealerDataArea(loginUser.getDataArea());
		Department dept =  DepartmentQuery.me().findByDataArea(dept_dataArea);
		sellerCustomer.set("data_area", dept_dataArea);
		sellerCustomer.set("dept_id", dept.getId());
		if (StrKit.isBlank(sellerCustomer.getId())) {
			sellerCustomerId = StrKit.getRandomUUID();
			sellerCustomer.set("id", sellerCustomerId);
			sellerCustomer.set("create_date", new Date());
			sellerCustomer.save();
		} else {
			sellerCustomerId = sellerCustomer.getId();
			sellerCustomer.set("modify_date", new Date());
			sellerCustomer.update();
		}

		CustomerJoinCustomerTypeQuery.me().deleteBySellerCustomerId(sellerCustomerId);

		String[] customerTypes = getParaValues("customerTypes");
		for (String custType : customerTypes) {
			CustomerJoinCustomerType ccType = new CustomerJoinCustomerType();
			ccType.setSellerCustomerId(sellerCustomerId);
			ccType.setCustomerTypeId(custType);
			ccType.save();
		}

		String _userIds = getPara("userIds");

		if (StrKit.isBlank(_userIds)) {// 业务员修改时
			User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
			UserJoinCustomerQuery.me().deleteBySelerCustomerIdAndUserId(sellerCustomerId, user.getId());
			_userIds = user.getId();
		} else {
			UserJoinCustomerQuery.me().deleteBySelerCustomerId(sellerCustomerId);
		}

		String[] userIdArray = _userIds.split(",");

		for (String userId : userIdArray) {

			User user = UserQuery.me().findById(userId);
			UserJoinCustomer uCustomer = new UserJoinCustomer();

			uCustomer.setSellerCustomerId(sellerCustomerId);
			uCustomer.setUserId(userId);
			uCustomer.setDeptId(user.getDepartmentId());
			uCustomer.setDataArea(user.getDataArea());

			uCustomer.save();
		}

		renderAjaxResultForSuccess();
	}

	public void user_tree() {

		String dataArea = getSessionAttr(Consts.SESSION_SELECT_DATAAREA);
		List<Map<String, Object>> treeData = DepartmentQuery.me().findDeptListAsTree(dataArea, true);
		setAttr("treeData", JSON.toJSON(treeData));

	}

	public void department_tree() {

		String dataArea = getSessionAttr(Consts.SESSION_SELECT_DATAAREA);
		List<Map<String, Object>> treeData = DepartmentQuery.me().findDeptListAsTree(dataArea, false);
		setAttr("treeData", JSON.toJSON(treeData));
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/downloading", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void download() {

		render("download.html");
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/downloading", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void downloading() throws UnsupportedEncodingException {

		String dataArea = getPara("data_area");

		String filePath = getSession().getServletContext().getRealPath("\\") + "\\WEB-INF\\admin\\seller_customer\\"
				+ "customerInfo.xlsx";

		Page<Record> page = SellerCustomerQuery.me().paginate(1, Integer.MAX_VALUE, "", dataArea + "%");
		List<Record> customerList = page.getList();

		List<CustomerExcel> excellist = Lists.newArrayList();
		for (Record record : customerList) {

			CustomerExcel excel = new CustomerExcel();
			excel.setCustomerName((String) record.get("customer_name"));
			excel.setNickname((String) record.get("nickname"));
			excel.setContact((String) record.get("contact"));
			excel.setMobile((String) record.get("mobile"));
			excel.setEmail((String) record.get("email"));
			excel.setProvName((String) record.get("prov_name"));
			excel.setCityName((String) record.get("city_name"));
			excel.setCountyName((String) record.get("country_name"));
			excel.setAddress((String) record.get("address"));
			excel.setCustomerTypeName((String) record.get("customerTypeNames"));

			excellist.add(excel);
		}

		ExportParams params = new ExportParams();
		Workbook wb = ExcelExportUtil.exportBigExcel(params, CustomerExcel.class, excellist);
		File file = new File(filePath);
		FileOutputStream out = null;
		try {
			out = new FileOutputStream(file);
			wb.write(out);
			out.flush();
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				out.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		
		ExcelExportUtil.closeExportBigExcel();

		renderFile(new File(filePath));
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/uploading", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void upload() {

		render("upload.html");
	}

	@RequiresPermissions(value = { "/admin/sellerCustomer/uploading", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void customerTemplate() {
		String realPath = getSession().getServletContext().getRealPath("\\");
		renderFile(new File(realPath + "\\WEB-INF\\admin\\seller_customer\\customerTemplate.xlsx"));
	}

	@Before(Tx.class)
	@RequiresPermissions(value = { "/admin/sellerCustomer/uploading", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void uploading() {
		int inCnt = 0;
		int existCnt = 0;

		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		String sellerId = getSessionAttr("sellerId");
		String dataArea = getSessionAttr(Consts.SESSION_SELECT_DATAAREA);
		String dept_dataArea = DataAreaUtil.getUserDealerDataArea(user.getDataArea());
		Department dept =  DepartmentQuery.me().findByDataArea(dept_dataArea);
		
		File file = getFile().getFile();
		String userId = getPara("userIds");
		ImportParams params = new ImportParams();

		List<CustomerExcel> list = ExcelImportUtil.importExcel(file, CustomerExcel.class, params);

		for (CustomerExcel excel : list) {
			String customerId = "";
			String sellerCustomerId = "";
			SellerCustomer sellerCustomer = null;

			// 检查客户是否存在
			Customer customer = CustomerQuery.me().findByCustomerNameAndMobile(excel.getCustomerName(),
					excel.getMobile());

			if (customer == null) {
				customer = new Customer();
				customerId = StrKit.getRandomUUID();
				customer.set("id", customerId);
				this.setCustomer(customer, excel);
				customer.set("create_date", new Date());
				customer.save();
			} else {
				customerId = customer.getId();
				// 检查客户是否存在我销售商的客户中
				sellerCustomerId = SellerCustomerQuery.me().findsellerCustomerBycusId(customerId, dataArea);
			}

			if (StrKit.isBlank(sellerCustomerId)) {
				sellerCustomerId = StrKit.getRandomUUID();
				sellerCustomer = new SellerCustomer();
				sellerCustomer.set("id", sellerCustomerId);
				sellerCustomer.set("seller_id", sellerId);
				sellerCustomer.set("customer_id", customerId);
				sellerCustomer.set("is_enabled", 1);
				sellerCustomer.set("is_archive", 1);
				sellerCustomer.set("sub_type", 100301);
				sellerCustomer.set("customer_kind", 100401);
				sellerCustomer.set("nickname", excel.getNickname());
				sellerCustomer.set("data_area", dept_dataArea);
				sellerCustomer.set("dept_id", dept.getId());
				sellerCustomer.set("create_date", new Date());
				sellerCustomer.save();
				inCnt++;
			} else {
				existCnt++;
			}

			UserJoinCustomerQuery.me().deleteBySelerCustomerId(sellerCustomerId);
			this.insertUserJoinCustomer(sellerCustomerId, userId);
			CustomerJoinCustomerTypeQuery.me().deleteBySellerCustomerId(sellerCustomerId);
			this.insertCustomerJoinCustomerType(sellerCustomerId, excel, user);

		}

		renderAjaxResultForSuccess("成功导入客户" + inCnt + "个,已存在客户" + existCnt + "个");
	}

	private void setCustomer(Customer customer, CustomerExcel excel) {
		customer.set("customer_name", excel.getCustomerName());
		customer.set("contact", excel.getContact());
		customer.set("mobile", excel.getMobile());
		customer.set("email", excel.getEmail());
		customer.set("prov_name", excel.getProvName());
		customer.set("city_name", excel.getCityName());
		customer.set("country_name", excel.getCountyName());
		customer.set("address", excel.getAddress());
	}

	private void insertCustomerJoinCustomerType(String sellerCustomerId, CustomerExcel excel, User user) {

		String customerTypeName = excel.getCustomerTypeName();
		String[] customerTypeNames = customerTypeName.split(",");
		for (String typeName : customerTypeNames) {
			String id = CustomerTypeQuery.me().findIdByName(typeName,
					DataAreaUtil.getUserDealerDataArea(user.getDataArea()));
			if (StrKit.isBlank(id)) {
				renderAjaxResultForError("你还没有创建这个客户类型：" + typeName + ", 请确认");
			}
			CustomerJoinCustomerTypeQuery.me().insert(sellerCustomerId, id);
		}
	}

	private void insertUserJoinCustomer(String sellerCustomerId, String userIds) {
		String[] userIdArray = userIds.split(",");
		for (String id : userIdArray) {
			User user = UserQuery.me().findById(id);
			UserJoinCustomerQuery.me().insert(sellerCustomerId, id, user.getDepartmentId(), user.getDataArea());
		}
	}

	@Before(Tx.class)
	@RequiresPermissions(value = { "/admin/sellerCustomer/batchSetUser", "/admin/dealer/all",
			"/admin/all" }, logical = Logical.OR)
	public void batchSetUser() {
		String[] sellerCustomerIds = getParaValues("dataItem");
		String[] userIds = getParaValues("userIds");
		for (String sellerCustomerId : sellerCustomerIds) {
			UserJoinCustomerQuery.me().deleteBySelerCustomerId(sellerCustomerId);
			for (String userId : userIds)
				this.insertUserJoinCustomer(sellerCustomerId, userId);
		}

		renderAjaxResultForSuccess();
	}
	
	public void searchByCustomerName() {
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		String dept_dataArea = DataAreaUtil.getUserDealerDataArea(user.getDataArea());
		if(StrKit.isBlank(dept_dataArea)) {
			renderAjaxResultForError("丢失组织数据");
			return ;
		}
		Department dept =  DepartmentQuery.me().findByDataArea(dept_dataArea);
		if(dept==null||StrKit.isBlank(dept.getId())) {
			renderAjaxResultForError("丢失组织结构数据");
			return ;
		}
		String tCustomerName = getPara("name");
		renderAjaxResultForSuccess("success",JSON.toJSON(CustomerQuery.me().findByCustomerName(dept_dataArea, dept.getId(), tCustomerName)));
	}
	
	public void searchTypeById() {
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		String dept_dataArea = DataAreaUtil.getUserDealerDataArea(user.getDataArea());
		String sellerCustomerId = getPara("sellerC_Id");
		List<Record> list = UserJoinCustomerQuery.me().findCustomerTypeBySellerCustomerId(sellerCustomerId, dept_dataArea+"%");
		renderAjaxResultForSuccess("success",JSON.toJSON(list));

	}

}
