/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.controller.admin;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.ccloud.Consts;
import org.ccloud.core.JBaseCRUDController;
import org.ccloud.core.interceptor.ActionCacheClearInterceptor;
import org.ccloud.model.Inventory;
import org.ccloud.model.InventoryDetail;
import org.ccloud.model.StockTaking;
import org.ccloud.model.StockTakingDetail;
import org.ccloud.model.User;
import org.ccloud.model.Warehouse;
import org.ccloud.model.query.InventoryQuery;
import org.ccloud.model.query.StockTakingDetailQuery;
import org.ccloud.model.query.StockTakingQuery;
import org.ccloud.model.query.UserQuery;
import org.ccloud.model.query.WarehouseQuery;
import org.ccloud.model.vo.StockTakingInfo;
import org.ccloud.route.RouterMapping;
import org.ccloud.route.RouterNotAllowConvert;
import org.ccloud.utils.DateUtils;
import org.ccloud.utils.StringUtils;

import com.google.common.collect.ImmutableMap;
import com.jfinal.aop.Before;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by 九毫米(http://9mm.tech).
 */
@RouterMapping(url = "/admin/stockTaking", viewPath = "/WEB-INF/admin/stock_taking")
@Before(ActionCacheClearInterceptor.class)
@RouterNotAllowConvert
public class _StockTakingController extends JBaseCRUDController<StockTaking> {

	public static final String BILLTYPE = "ST";
	// 目前系统还没有企业编号，先创建一个100000占位
	public static final String COMPANYCODE = "100000";

	public void list() {
		String keyword = getPara("k");
		if (StrKit.notBlank(keyword)) {
			keyword = StringUtils.urlDecode(keyword);
			setAttr("k", keyword);
		}
		String seller_id=getSessionAttr("sellerId").toString();
		Page<StockTaking> page = StockTakingQuery.me().paginate(getPageNumber(), getPageSize(), keyword,seller_id,"c.create_date");
		Map<String, Object> map = ImmutableMap.of("total", page.getTotalRow(), "rows", page.getList());
		renderJson(map);
	}

	public void edit() {
		String id = getPara("id");
		User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
		String userId = user.getId();
		if (id != null) {
			StockTaking stockTaking = StockTakingQuery.me().findById(id);
			setAttr("stockTaking", stockTaking);
		}
		List<Warehouse> wlist = WarehouseQuery.me().findWarehouseByUserId(userId);
		setAttr("wlist", wlist);
		List<User> ulist = UserQuery.me().findUserList(userId);
		setAttr("ulist", ulist);
		List<StockTakingInfo> ilist = StockTakingDetailQuery.me().findByStockTakingDetailId(id);
		setAttr("ilist", ilist);
	}

	public void enable() {
		String id = getPara("id");
		int isEnabled = getParaToInt("isEnabled");
		StockTaking stockTaking = StockTakingQuery.me().findById(id);
		Warehouse warehouse=WarehouseQuery.me().findById(stockTaking.getWarehouseId());
		warehouse.setIsInited(1);
		warehouse.update();
		stockTaking.setStatus(isEnabled);
		if (stockTaking.saveOrUpdate()) {
			List<Map<String, Object>>listMap=StockTakingDetailQuery.me().findByStockTakingDetailId1(id);
			for (int i = 0; i < listMap.size(); i++) {
				Inventory inventory=new Inventory();
				InventoryDetail inventoryDetail=new InventoryDetail();
				List<Record> findByInventory = StockTakingDetailQuery.me().findByInventory((String) listMap.get(i).get("product_id"),stockTaking.getWarehouseId(),stockTaking.getSellerId());
				String sell_product_id= StockTakingDetailQuery.me().selectSellProductId((String) listMap.get(i).get("product_id"),stockTaking.getSellerId());
				if (findByInventory.size()!=0) {
					inventory=InventoryQuery.me().findById(findByInventory.get(0).getStr("id"));
					inventory.setInCount( inventory.getInCount().add(new BigDecimal(listMap.get(i).get("product_count").toString())));
					inventory.setInAmount(inventory.getInAmount().add(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString()))));
					inventory.setModifyDate(new Date());
					inventory.setBalanceCount(inventory.getBalanceCount().add(new BigDecimal(listMap.get(i).get("product_count").toString())));
					inventory.setBalanceAmount(inventory.getBalanceAmount().add(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString()))));
					inventory.update();
				}else {
					inventory.setId(StrKit.getRandomUUID());
					inventory.setWarehouseId(stockTaking.getWarehouseId());
					inventory.setProductId((String) listMap.get(i).get("product_id"));
					inventory.setSellerId(stockTaking.getSellerId());
					inventory.setInCount( new BigDecimal(listMap.get(i).get("product_count").toString()));
					inventory.setInAmount(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString())));
					inventory.setInPrice(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("convert_relate").toString())));
					inventory.setBalanceCount( new BigDecimal(listMap.get(i).get("product_count").toString()));
					inventory.setBalanceAmount(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString())));
					inventory.setBalancePrice(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("convert_relate").toString())));
					inventory.setDataArea(stockTaking.getDataArea());
					inventory.setDeptId(stockTaking.getDeptId());
					inventory.setCreateDate(new Date());
					inventory.save();
				}
				inventoryDetail.setId(StrKit.getRandomUUID());
				inventoryDetail.setWarehouseId(stockTaking.getWarehouseId());
				inventoryDetail.setSellProductId(sell_product_id);
				inventoryDetail.setInCount(new BigDecimal(listMap.get(i).get("product_count").toString()));
				inventoryDetail.setInAmount(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString())));
				inventoryDetail.setInPrice(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("convert_relate").toString())));
				inventoryDetail.setBalanceCount(new BigDecimal(listMap.get(i).get("product_count").toString()));
				inventoryDetail.setBalanceAmount(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("product_count").toString())));
				inventoryDetail.setBalancePrice(new BigDecimal(listMap.get(i).get("market_price").toString()).multiply(new BigDecimal(listMap.get(i).get("convert_relate").toString())));
				inventoryDetail.setBizType("100208");
				inventoryDetail.setBizBillSn(stockTaking.getStockTakingSn());
				inventoryDetail.setBizDate(stockTaking.getBizDate());
				inventoryDetail.setBizUserId(stockTaking.getBizUserId());
				inventoryDetail.setRemark((String) listMap.get(i).get("remark"));
				inventoryDetail.setDataArea(stockTaking.getDataArea());
				inventoryDetail.setDeptId(stockTaking.getDeptId());
				inventoryDetail.setCreateDate(new Date());
				inventoryDetail.save();
			}
			renderAjaxResultForSuccess("更新成功");
		} else {
			renderAjaxResultForError("更新失败");
		}
	}

	@Override
	public void save() {
		StockTaking stockTaking = getModel(StockTaking.class);
		if (stockTaking.getStatus() == null || stockTaking.getStatus() == 0) {
			User user = getSessionAttr(Consts.SESSION_LOGINED_USER);
			stockTaking.setDeptId(user.getDepartmentId());
			stockTaking.setDataArea(user.getDataArea());
			stockTaking.setInputUserId(user.getId());
			stockTaking.setSellerId( getSessionAttr("sellerId").toString());
			Map<String, String[]> map = getParaMap();
			boolean update = false;
			if (StringUtils.isBlank(stockTaking.getId())) {
				stockTaking.setId(StrKit.getRandomUUID());
				stockTaking.setCreateDate(new Date());
				stockTaking.setBizDate(new Date());
				stockTaking.setStatus(0);
				String billno = this.getBillSn();
				stockTaking.setStockTakingSn(billno);
			} else {
				update = true;
			}
			boolean status = this.saveStockTakingInfo(map, stockTaking, update);
			if (status) {
				renderAjaxResultForSuccess("ok");
			}
		} else {
			renderAjaxResultForError("保存失败,该单子已盘点完成！");
		}
	}

	public boolean saveStockTakingInfo(final Map<String, String[]> map, final StockTaking stockTaking,
			final boolean update) {
		boolean isSave = Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				if (update) {
					stockTaking.saveOrUpdate();
					List<StockTakingDetail> iSaveList = new ArrayList<>();
					int loopEnd = 1;
					// 先根据主表ID，删除盘点单子表相关记录
					List<StockTakingDetail> list = StockTakingDetailQuery.me()
							.deleteByStockTakingId(stockTaking.getId());
					for (StockTakingDetail stockTakingDetail : list) {
						stockTakingDetail.delete();
					}
					// 再把修改的内容插入子表
					String[] factIndex = map.get("factIndex");
					for (int i = 1; i < factIndex.length; i++) {
						StockTakingDetail stockTakingDetail = getModel(StockTakingDetail.class);
						String productId = StringUtils
								.getArrayFirst(map.get("stockTakingList[" + factIndex[i] + "].product_id"));
						String productCount = StringUtils
								.getArrayFirst(map.get("stockTakingList[" + factIndex[i] + "].product_count"));
						String remark = StringUtils
								.getArrayFirst(map.get("stockTakingList[" + factIndex[i] + "].remark"));
						stockTakingDetail.setProductId(productId);
						stockTakingDetail.setProductCount(Integer.parseInt(productCount));
						stockTakingDetail.setRemark(remark);
						stockTakingDetail.setStockTakingId(stockTaking.getId());
						stockTakingDetail.setId(StrKit.getRandomUUID());
						stockTakingDetail.setProductAmount(BigDecimal.valueOf(10000));
						stockTakingDetail.setDeptId(stockTaking.getDeptId());
						stockTakingDetail.setDataArea(stockTaking.getDataArea());
						stockTakingDetail.setCreateDate(stockTaking.getCreateDate());
						stockTakingDetail.setModifyDate(new Date());
						iSaveList.add(stockTakingDetail);
						loopEnd++;
						if (loopEnd == factIndex.length) {
							break;
						}
					}
					try {
						Db.batchSave(iSaveList, iSaveList.size());
					} catch (Exception e) {
						e.printStackTrace();
						return false;
					}
				} else {
					stockTaking.save();
					// 存储盘点单子表信息
					List<StockTakingDetail> iSaveList = new ArrayList<>();
					String[] factIndex = map.get("factIndex");
					int loopEnd = 1;
					for (int i = 0; i < factIndex.length; i++) {
						StockTakingDetail stockTakingDetail = getModel(StockTakingDetail.class);
						String productId = StringUtils.getArrayFirst(map.get("stockTakingList[" + i + "].product_id"));
						String productCount = StringUtils
								.getArrayFirst(map.get("stockTakingList[" + i + "].product_count"));
						String remark = StringUtils.getArrayFirst(map.get("stockTakingList[" + i + "].remark"));

						stockTakingDetail.setProductId(productId);
						stockTakingDetail.setProductCount(Integer.parseInt(productCount));
						stockTakingDetail.setRemark(remark);
						stockTakingDetail.setStockTakingId(stockTaking.getId());
						stockTakingDetail.setId(StrKit.getRandomUUID());
						stockTakingDetail.setProductAmount(BigDecimal.valueOf(10000));
						stockTakingDetail.setDeptId(stockTaking.getDeptId());
						stockTakingDetail.setDataArea(stockTaking.getDataArea());
						stockTakingDetail.setCreateDate(new Date());
						iSaveList.add(stockTakingDetail);
						loopEnd++;
						if (loopEnd == factIndex.length) {
							break;
						}
					}
					try {
						Db.batchSave(iSaveList, iSaveList.size());
					} catch (Exception e) {
						e.printStackTrace();
						return false;
					}
				}
				return true;
			}
		});
		return isSave;
	}

	// 删除盘点单主表及其子表的信息
	@Override
	public void delete() {
		String id = getPara("id");
		final StockTaking stockTaking = StockTakingQuery.me().findById(id);
		boolean status = StockTakingQuery.me().deleteAbout(stockTaking);
		if (status) {
			renderAjaxResultForSuccess("ok");
		}
	}

	// 通过数据库查最大的单据号加1返回去
	public String getBillSn() {
		int newNo = 0;
		List<Integer> list = new ArrayList<>();
		String startNo = "000001";
		StringBuilder sBuilder = new StringBuilder(BILLTYPE);
		sBuilder.append(COMPANYCODE);
		String Number = DateUtils.dateString();
		// 查询数据库当天最大的单据号，并在此基础上加1
		SimpleDateFormat sdf = new SimpleDateFormat(DateUtils.DEFAULT_NORMAL_FORMATTER);
		String today = null;
		today = sdf.format(new Date());
		sBuilder.append(Number);
		List<StockTaking> stockTakings = StockTakingQuery.me().findByBillSn(today);
		// 如果为空说明是每天的第一次插入数据，则后三位的话从1开始，即001开始
		if (stockTakings.size() == 0) {
			sBuilder.append(startNo);
			return sBuilder.toString();
		}
		// 获取当天的所有单据号，并截取后三位来进行比大小，找出最大的那位
		for (StockTaking stockTaking : stockTakings) {
			stockTaking.setStockTakingSn(stockTaking.getStockTakingSn().substring(16));
			list.add(Integer.valueOf(stockTaking.getStockTakingSn()));
		}
		Integer arr[] = new Integer[list.size()];
		for (int i = 0; i < list.size(); i++) {
			arr[i] = list.get(i);
		}
		// 比较找出单据号最大的那位
		int max = arr[0];
		for (int i = 0; i < arr.length; i++) {
			if (arr[i] > max) {
				max = arr[i];
			}
		}
		newNo = max + 1;
		// 如果单据号是个位数，前面要补一个0
		if (newNo <= 9) {
			sBuilder.append("00000");
			sBuilder.append(String.valueOf(newNo));
		} else if (newNo <= 99) {
			sBuilder.append("0000");
			sBuilder.append(String.valueOf(newNo));
		} else {
			sBuilder.append(String.valueOf(newNo));
		}

		return sBuilder.toString();
	}

}
