/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model.base;

import org.ccloud.message.MessageKit;
import org.ccloud.model.core.JModel;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by 九毫米(http://9mm.tech), do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockFact<M extends BaseStockFact<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "stock_fact";
	public static final String METADATA_TYPE = "stock_fact";

	public static final String ACTION_ADD = "stock_fact:add";
	public static final String ACTION_DELETE = "stock_fact:delete";
	public static final String ACTION_UPDATE = "stock_fact:update";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseStockFact<?>)){return false;}

		BaseStockFact<?> m = (BaseStockFact<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setDealerCode(java.lang.String dealerCode) {
		set("dealerCode", dealerCode);
	}

	public java.lang.String getDealerCode() {
		return get("dealerCode");
	}

	public void setDealerName(java.lang.String dealerName) {
		set("dealerName", dealerName);
	}

	public java.lang.String getDealerName() {
		return get("dealerName");
	}

	public void setSellerCode(java.lang.String sellerCode) {
		set("sellerCode", sellerCode);
	}

	public java.lang.String getSellerCode() {
		return get("sellerCode");
	}

	public void setSellerName(java.lang.String sellerName) {
		set("sellerName", sellerName);
	}

	public java.lang.String getSellerName() {
		return get("sellerName");
	}

	public void setIdate(java.util.Date idate) {
		set("idate", idate);
	}

	public java.util.Date getIdate() {
		return get("idate");
	}

	public void setCInvCode(java.lang.String cInvCode) {
		set("cInvCode", cInvCode);
	}

	public java.lang.String getCInvCode() {
		return get("cInvCode");
	}

	public void setCINVName(java.lang.String cINVName) {
		set("cINVName", cINVName);
	}

	public java.lang.String getCINVName() {
		return get("cINVName");
	}

	public void setCInvCCode(java.lang.String cInvCCode) {
		set("cInvCCode", cInvCCode);
	}

	public java.lang.String getCInvCCode() {
		return get("cInvCCode");
	}

	public void setCInvCName(java.lang.String cInvCName) {
		set("cInvCName", cInvCName);
	}

	public java.lang.String getCInvCName() {
		return get("cInvCName");
	}

	public void setCInvStd(java.lang.String cInvStd) {
		set("cInvStd", cInvStd);
	}

	public java.lang.String getCInvStd() {
		return get("cInvStd");
	}

	public void setCInvUnit(java.lang.String cInvUnit) {
		set("cInvUnit", cInvUnit);
	}

	public java.lang.String getCInvUnit() {
		return get("cInvUnit");
	}

	public void setCInvMUnit(java.lang.String cInvMUnit) {
		set("cInvMUnit", cInvMUnit);
	}

	public java.lang.String getCInvMUnit() {
		return get("cInvMUnit");
	}

	public void setCInvMNum(java.lang.Integer cInvMNum) {
		set("cInvMNum", cInvMNum);
	}

	public java.lang.Integer getCInvMNum() {
		return get("cInvMNum");
	}

	public void setProvCode(java.lang.String provCode) {
		set("provCode", provCode);
	}

	public java.lang.String getProvCode() {
		return get("provCode");
	}

	public void setProvName(java.lang.String provName) {
		set("provName", provName);
	}

	public java.lang.String getProvName() {
		return get("provName");
	}

	public void setCityCode(java.lang.String cityCode) {
		set("cityCode", cityCode);
	}

	public java.lang.String getCityCode() {
		return get("cityCode");
	}

	public void setCityName(java.lang.String cityName) {
		set("cityName", cityName);
	}

	public java.lang.String getCityName() {
		return get("cityName");
	}

	public void setCountryCode(java.lang.String countryCode) {
		set("countryCode", countryCode);
	}

	public java.lang.String getCountryCode() {
		return get("countryCode");
	}

	public void setCountryName(java.lang.String countryName) {
		set("countryName", countryName);
	}

	public java.lang.String getCountryName() {
		return get("countryName");
	}

	public void setBigAmount(java.lang.Integer bigAmount) {
		set("bigAmount", bigAmount);
	}

	public java.lang.Integer getBigAmount() {
		return get("bigAmount");
	}

	public void setSmallAmount(java.lang.Integer smallAmount) {
		set("smallAmount", smallAmount);
	}

	public java.lang.Integer getSmallAmount() {
		return get("smallAmount");
	}

	public void setTotalSmallAmount(java.lang.Integer totalSmallAmount) {
		set("totalSmallAmount", totalSmallAmount);
	}

	public java.lang.Integer getTotalSmallAmount() {
		return get("totalSmallAmount");
	}

}
