/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model.query;

import java.util.LinkedList;
import java.util.List;

import org.ccloud.model.Member;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 * Generated by 九毫米(http://9mm.tech).
 */
public class MemberQuery extends JBaseQuery { 

	protected static final Member DAO = new Member();
	private static final MemberQuery QUERY = new MemberQuery();

	public static MemberQuery me() {
		return QUERY;
	}

	public Member findById(final String id) {
		return DAO.getCache(id, new IDataLoader() {
			@Override
			public Object load() {
				return DAO.findById(id);
			}
		});
	}

	public Page<Member> paginate(int pageNumber, int pageSize, String orderby) {
		String select = "select * ";
		StringBuilder fromBuilder = new StringBuilder("from `cc_member` ");

		LinkedList<Object> params = new LinkedList<Object>();

		if (params.isEmpty())
			return DAO.paginate(pageNumber, pageSize, select, fromBuilder.toString());

		return DAO.paginate(pageNumber, pageSize, select, fromBuilder.toString(), params.toArray());
	}

	public int batchDelete(String... ids) {
		if (ids != null && ids.length > 0) {
			int deleteCount = 0;
			for (int i = 0; i < ids.length; i++) {
				if (DAO.deleteById(ids[i])) {
					++deleteCount;
				}
			}
			return deleteCount;
		}
		return 0;
	}

	public Member findByWechatOpenid(final String openid) {
		return DAO.doFindFirst("wechat_open_id = ? AND status = 1", openid);
	}

	public List<Record> checkCustomerExist(String mobile,String sales_id) {
		StringBuilder sqlBuilder = new StringBuilder("select c.*");
		sqlBuilder.append("from `cc_customer` c ");
		sqlBuilder.append("join cc_seller_customer sc on c.id = sc.customer_id ");
		sqlBuilder.append("join cc_user_join_customer ujc on sc.id = ujc.seller_customer_id ");
		sqlBuilder.append("where c.mobile = ? AND sc.is_enabled = 1 AND ujc.user_id = ?");
		return Db.find(sqlBuilder.toString(), mobile, sales_id);
	}

	public Member checkMemberExist(String mobile,String sales_id) {
		StringBuilder sqlBuilder = new StringBuilder("select m.*");
		sqlBuilder.append("from cc_member m ");
		sqlBuilder.append("JOIN cc_customer c ON m.customer_id = c.id ");
		sqlBuilder.append("join cc_seller_customer sc on c.id = sc.customer_id ");
		sqlBuilder.append("join cc_user_join_customer ujc on sc.id = ujc.seller_customer_id ");
		sqlBuilder.append("where c.mobile = ? AND sc.is_enabled = 1 AND ujc.user_id = ?");
		return DAO.findFirst(sqlBuilder.toString(), mobile, sales_id);
	}

	public List<Member> findByMobile(String mobile) {
		StringBuilder sqlBuilder = new StringBuilder("select * ");
		sqlBuilder.append("from `cc_member` ");
		sqlBuilder.append("where mobile = ? AND status = 1");
		return DAO.find(sqlBuilder.toString(), mobile);
	}
}
