/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model;

import org.ccloud.model.core.Table;
import org.ccloud.model.base.BaseUserJoinCustomer;

/**
 * Generated by 九毫米(http://9mm.tech).
 */
@Table(tableName="cc_user_join_customer",primaryKey="customer_id,user_id")
public class UserJoinCustomer extends BaseUserJoinCustomer<UserJoinCustomer> {

	private static final long serialVersionUID = 1L;

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final UserJoinCustomer other = (UserJoinCustomer) obj;
		if (getUserId() != null && other.getUserId() != null && 
				getCustomerId() != null && other.getCustomerId() != null)
			return getUserId().equals(other.getUserId()) && 
					getCustomerId().equals(other.getCustomerId());
		return false;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode()) 
				+ ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
		return result;
	}
}
