/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model.base;

import org.ccloud.message.MessageKit;
import org.ccloud.model.core.JModel;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by 九毫米(http://9mm.tech), do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalesRefundInstockDetail<M extends BaseSalesRefundInstockDetail<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "cc_sales_refund_instock_detail";
	public static final String METADATA_TYPE = "cc_sales_refund_instock_detail";

	public static final String ACTION_ADD = "cc_sales_refund_instock_detail:add";
	public static final String ACTION_DELETE = "cc_sales_refund_instock_detail:delete";
	public static final String ACTION_UPDATE = "cc_sales_refund_instock_detail:update";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseSalesRefundInstockDetail<?>)){return false;}

		BaseSalesRefundInstockDetail<?> m = (BaseSalesRefundInstockDetail<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setProductId(java.lang.String productId) {
		set("product_id", productId);
	}

	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public void setRefundInstockId(java.lang.String refundInstockId) {
		set("refund_instock_id", refundInstockId);
	}

	public java.lang.String getRefundInstockId() {
		return getStr("refund_instock_id");
	}

	public void setProductCount(java.lang.String productCount) {
		set("product_count", productCount);
	}

	public java.lang.String getProductCount() {
		return getStr("product_count");
	}

	public void setProductAmount(java.lang.String productAmount) {
		set("product_amount", productAmount);
	}

	public java.lang.String getProductAmount() {
		return getStr("product_amount");
	}

	public void setProductPrice(java.lang.String productPrice) {
		set("product_price", productPrice);
	}

	public java.lang.String getProductPrice() {
		return getStr("product_price");
	}

	public void setCost(java.lang.String cost) {
		set("cost", cost);
	}

	public java.lang.String getCost() {
		return getStr("cost");
	}

	public void setTotalCost(java.lang.String totalCost) {
		set("total_cost", totalCost);
	}

	public java.lang.String getTotalCost() {
		return getStr("total_cost");
	}

	public void setOutstockDetailId(java.lang.String outstockDetailId) {
		set("outstock_detail_id", outstockDetailId);
	}

	public java.lang.String getOutstockDetailId() {
		return getStr("outstock_detail_id");
	}

	public void setRejectProductPrice(java.math.BigDecimal rejectProductPrice) {
		set("reject_product_price", rejectProductPrice);
	}

	public java.math.BigDecimal getRejectProductPrice() {
		return get("reject_product_price");
	}

	public void setRejectAmount(java.math.BigDecimal rejectAmount) {
		set("reject_amount", rejectAmount);
	}

	public java.math.BigDecimal getRejectAmount() {
		return get("reject_amount");
	}

	public void setRejectProductCount(java.lang.Integer rejectProductCount) {
		set("reject_product_count", rejectProductCount);
	}

	public java.lang.Integer getRejectProductCount() {
		return getInt("reject_product_count");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
	}

	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public void setDataArea(java.lang.String dataArea) {
		set("data_area", dataArea);
	}

	public java.lang.String getDataArea() {
		return getStr("data_area");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
