/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model.base;

import org.ccloud.cache.JCacheKit;
import org.ccloud.message.MessageKit;
import org.ccloud.model.core.JModel;
import com.jfinal.plugin.activerecord.IBean;

import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by 九毫米(http://9mm.tech), do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerStore<M extends BaseCustomerStore<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "cc_customer_store";
	public static final String METADATA_TYPE = "cc_customer_store";

	public static final String ACTION_ADD = "cc_customer_store:add";
	public static final String ACTION_DELETE = "cc_customer_store:delete";
	public static final String ACTION_UPDATE = "cc_customer_store:update";

	public void removeCache(Object key){
		if(key == null) return;
		JCacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		JCacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return JCacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return JCacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseCustomerStore<?>)){return false;}

		BaseCustomerStore<?> m = (BaseCustomerStore<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setProvName(java.lang.String provName) {
		set("prov_name", provName);
	}

	public java.lang.String getProvName() {
		return getStr("prov_name");
	}

	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}

	public java.lang.String getCityName() {
		return getStr("city_name");
	}

	public void setCountryName(java.lang.String countryName) {
		set("country_name", countryName);
	}

	public java.lang.String getCountryName() {
		return getStr("country_name");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setLng(java.math.BigDecimal lng) {
		set("lng", lng);
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public void setLat(java.math.BigDecimal lat) {
		set("lat", lat);
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}

	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setStreetId(java.lang.String streetId) {
		set("street_id", streetId);
	}

	public java.lang.String getStreetId() {
		return getStr("street_id");
	}

	public void setDetail(java.lang.Boolean detail) {
		set("detail", detail);
	}

	public java.lang.Boolean getDetail() {
		return get("detail");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}

	public java.lang.String getTag() {
		return getStr("tag");
	}

	public void setDetailUrl(java.lang.String detailUrl) {
		set("detail_url", detailUrl);
	}

	public java.lang.String getDetailUrl() {
		return getStr("detail_url");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOverallRating(java.math.BigDecimal overallRating) {
		set("overall_rating", overallRating);
	}

	public java.math.BigDecimal getOverallRating() {
		return get("overall_rating");
	}

	public void setCommentNum(java.lang.Integer commentNum) {
		set("comment_num", commentNum);
	}

	public java.lang.Integer getCommentNum() {
		return getInt("comment_num");
	}

	public void setGrouponNum(java.lang.Integer grouponNum) {
		set("groupon_num", grouponNum);
	}

	public java.lang.Integer getGrouponNum() {
		return getInt("groupon_num");
	}

	public void setPage(java.lang.Integer page) {
		set("page", page);
	}

	public java.lang.Integer getPage() {
		return getInt("page");
	}

	public void setIsEnabled(java.lang.Boolean isEnabled) {
		set("is_enabled", isEnabled);
	}

	public java.lang.Boolean getIsEnabled() {
		return get("is_enabled");
	}

	public void setReceiveNum(java.lang.Integer receiveNum) {
		set("receive_num", receiveNum);
	}

	public java.lang.Integer getReceiveNum() {
		return getInt("receive_num");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
