/**
 * Copyright (c) 2015-2016, Eric Huang 黄鑫 (hx50859042@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ccloud.model.base;

import java.util.List;

import org.ccloud.message.MessageKit;
import org.ccloud.model.CcGoodsSpecification;
import org.ccloud.model.core.JModel;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by 九毫米(http://9mm.tech), do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCcGoods<M extends BaseCcGoods<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "cc_goods";
	public static final String METADATA_TYPE = "cc_goods";

	public static final String ACTION_ADD = "cc_goods:add";
	public static final String ACTION_DELETE = "cc_goods:delete";
	public static final String ACTION_UPDATE = "cc_goods:update";
	
	private List<CcGoodsSpecification> specificationList;

	public List<CcGoodsSpecification> getSpecificationList() {
		return specificationList;
	}

	public void setSpecificationList(List<CcGoodsSpecification> specificationList) {
		this.specificationList = specificationList;
	}

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseCcGoods<?>)){return false;}

		BaseCcGoods<?> m = (BaseCcGoods<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setBrandId(java.lang.String brandId) {
		set("brand_id", brandId);
	}

	public java.lang.String getBrandId() {
		return get("brand_id");
	}

	public void setGoodsCategoryId(java.lang.String goodsCategoryId) {
		set("goods_category_id", goodsCategoryId);
	}

	public java.lang.String getGoodsCategoryId() {
		return get("goods_category_id");
	}

	public void setGoodsTypeId(java.lang.String goodsTypeId) {
		set("goods_type_id", goodsTypeId);
	}

	public java.lang.String getGoodsTypeId() {
		return get("goods_type_id");
	}

	public void setProductImageListStore(java.lang.String productImageListStore) {
		set("product_image_list_store", productImageListStore);
	}

	public java.lang.String getProductImageListStore() {
		return get("product_image_list_store");
	}

	public void setHtmlFilePath(java.lang.String htmlFilePath) {
		set("html_file_path", htmlFilePath);
	}

	public java.lang.String getHtmlFilePath() {
		return get("html_file_path");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setMetaDescription(java.lang.String metaDescription) {
		set("meta_description", metaDescription);
	}

	public java.lang.String getMetaDescription() {
		return get("meta_description");
	}

	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

	public java.lang.String getMetaKeywords() {
		return get("meta_keywords");
	}

	public void setBigPrice(java.math.BigDecimal bigPrice) {
		set("big_price", bigPrice);
	}

	public java.math.BigDecimal getBigPrice() {
		return get("big_price");
	}

	public void setSmallPrice(java.math.BigDecimal smallPrice) {
		set("small_price", smallPrice);
	}

	public java.math.BigDecimal getSmallPrice() {
		return get("small_price");
	}

	public void setSpecification(java.lang.String specification) {
		set("specification", specification);
	}

	public java.lang.String getSpecification() {
		return get("specification");
	}

	public void setBigUnit(java.lang.String bigUnit) {
		set("big_unit", bigUnit);
	}

	public java.lang.String getBigUnit() {
		return get("big_unit");
	}

	public void setSmallUnit(java.lang.String smallUnit) {
		set("small_unit", smallUnit);
	}

	public java.lang.String getSmallUnit() {
		return get("small_unit");
	}

	public void setConvertRelate(java.lang.Integer convertRelate) {
		set("convert_relate", convertRelate);
	}

	public java.lang.Integer getConvertRelate() {
		return get("convert_relate");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
